import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { CorruptStateFileError } from "../errors.js";

export interface CloneStateNoteEntry {
  file: string;
  recordChangeTag: string;
  modificationDate: number;
  /**
   * For a note shared *with* this account: the sharer's ownerRecordName,
   * i.e. which shared-database zone the note lives in. Absent for the
   * account's own (private-database) notes.
   */
  sharedZoneOwner?: string | undefined;
  /**
   * Set when this note contains content this tool couldn't fully parse (an
   * unresolvable embed, or unrecognized structure) - see the Safety
   * Guarantee Audit dev notes. Purely informational: `push` never trusts
   * this field, re-deriving the same check fresh from the live remote
   * record every time. Absent when the note is fully publishable.
   */
  unpublishableReason?: string | undefined;
}

export interface CloneStateAttachmentEntry {
  /** Path relative to the vault root, e.g. "attachments/_7130093.jpeg". */
  file: string;
  /** The `Media` record backing this attachment's actual bytes (distinct
   * from the `Attachment` record this entry is keyed by - see dev notes). */
  mediaRecordName: string;
  /** The Media record's `Asset.fileChecksum` as of the last download - the
   * change-detection signal `pull` compares against before re-downloading. */
  mediaFileChecksum: string;
  /** Which note this attachment belongs to, so it can be cleaned up if that
   * note is deleted or dropped from tracking. */
  noteRecordName: string;
}

export interface CloneStateAccount {
  appleId: string;
  dsid: string;
}

export interface CloneState {
  /**
   * Which Apple ID this folder was cloned for - resolves to that account's
   * own session under `~/.config/icloud-notes-sync/accounts/<dsid>/` (see
   * `accountStore.ts`), never anything secret stored here. Absent only for
   * folders cloned before per-folder account binding existed; `pull`/`push`/
   * `reauthenticate` refuse to run without it (see `UnboundAccountError`).
   */
  account?: CloneStateAccount | undefined;
  /** CloudKit syncToken as of this snapshot; a future `pull` resumes incremental sync from here. */
  syncToken: string | undefined;
  /**
   * Per-shared-zone syncTokens, keyed by the zone owner's recordName.
   * Absent entirely in state files written before shared-note support.
   */
  sharedZoneSyncTokens?: Record<string, string> | undefined;
  /**
   * This vault's identity in the Notes CRDT (base64 of 16 random bytes) -
   * text pushed from here is recorded in each note's replica table under
   * this id. Generated by the first `push` and stable per vault afterwards,
   * so repeated pushes read as one continuous editor rather than a parade
   * of one-shot replicas.
   */
  replicaId?: string | undefined;
  notes: Record<string, CloneStateNoteEntry>;
  /** Downloaded attachments, keyed by the `Attachment` record's recordName
   * (the identifier embedded in the owning note's body). Absent entirely in
   * state files written before Phase 4. */
  attachments?: Record<string, CloneStateAttachmentEntry> | undefined;
}

const STATE_DIR_NAME = ".icloud-notes-sync";
const STATE_FILE_NAME = "state.json";

export async function writeCloneState(targetDir: string, state: CloneState): Promise<void> {
  const dir = path.join(targetDir, STATE_DIR_NAME);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, STATE_FILE_NAME), JSON.stringify(state, null, 2) + "\n", "utf-8");
}

export async function readCloneState(targetDir: string): Promise<CloneState | undefined> {
  const filePath = path.join(targetDir, STATE_DIR_NAME, STATE_FILE_NAME);
  let raw: string;
  try {
    raw = await readFile(filePath, "utf-8");
  } catch (cause) {
    if (isEnoent(cause)) {
      return undefined;
    }
    throw cause;
  }

  const parsed: unknown = JSON.parse(raw);
  return assertCloneState(parsed, filePath);
}

function assertCloneState(value: unknown, filePath: string): CloneState {
  if (typeof value !== "object" || value === null || !isRecord(value) || !isRecord(value.notes)) {
    throw new CorruptStateFileError(`${filePath} does not look like a valid state file (missing "notes" object).`);
  }

  const syncToken = typeof value.syncToken === "string" ? value.syncToken : undefined;
  const notes: Record<string, CloneStateNoteEntry> = {};

  for (const [recordName, entry] of Object.entries(value.notes)) {
    if (
      !isRecord(entry) ||
      typeof entry.file !== "string" ||
      typeof entry.recordChangeTag !== "string" ||
      typeof entry.modificationDate !== "number"
    ) {
      throw new CorruptStateFileError(`${filePath} has a malformed entry for note "${recordName}".`);
    }
    notes[recordName] = {
      file: entry.file,
      recordChangeTag: entry.recordChangeTag,
      modificationDate: entry.modificationDate,
      sharedZoneOwner: typeof entry.sharedZoneOwner === "string" ? entry.sharedZoneOwner : undefined,
      unpublishableReason: typeof entry.unpublishableReason === "string" ? entry.unpublishableReason : undefined,
    };
  }

  const replicaId = typeof value.replicaId === "string" ? value.replicaId : undefined;

  let sharedZoneSyncTokens: Record<string, string> | undefined;
  if (isRecord(value.sharedZoneSyncTokens)) {
    sharedZoneSyncTokens = {};
    for (const [owner, token] of Object.entries(value.sharedZoneSyncTokens)) {
      if (typeof token !== "string") {
        throw new CorruptStateFileError(`${filePath} has a malformed shared-zone syncToken for owner "${owner}".`);
      }
      sharedZoneSyncTokens[owner] = token;
    }
  }

  let attachments: Record<string, CloneStateAttachmentEntry> | undefined;
  if (isRecord(value.attachments)) {
    attachments = {};
    for (const [recordName, entry] of Object.entries(value.attachments)) {
      if (
        !isRecord(entry) ||
        typeof entry.file !== "string" ||
        typeof entry.mediaRecordName !== "string" ||
        typeof entry.mediaFileChecksum !== "string" ||
        typeof entry.noteRecordName !== "string"
      ) {
        throw new CorruptStateFileError(`${filePath} has a malformed entry for attachment "${recordName}".`);
      }
      attachments[recordName] = {
        file: entry.file,
        mediaRecordName: entry.mediaRecordName,
        mediaFileChecksum: entry.mediaFileChecksum,
        noteRecordName: entry.noteRecordName,
      };
    }
  }

  let account: CloneStateAccount | undefined;
  if (value.account !== undefined) {
    if (!isRecord(value.account) || typeof value.account.appleId !== "string" || typeof value.account.dsid !== "string") {
      throw new CorruptStateFileError(`${filePath} has a malformed "account" field.`);
    }
    account = { appleId: value.account.appleId, dsid: value.account.dsid };
  }

  return { account, syncToken, sharedZoneSyncTokens, replicaId, notes, attachments };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isEnoent(err: unknown): boolean {
  return err instanceof Error && "code" in err && (err as NodeJS.ErrnoException).code === "ENOENT";
}
